spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración Hibernate / JPA para Producción
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
springdoc.swagger-ui.enabled=false
spring.devtools.add-properties=false
spring.jpa.open-in-view=false
springdoc.api-docs.enabled=false